apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: torrentofshame/backend
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              name: backend-port
          env:
            - name: FLASK_ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb://mongodb-service/coolappdb"
            - name: APP_SETTINGS
              value: "server.config.ProductionConfig"
  selector:
    matchLabels:
      app: backend
