version: "3.9"
services:
  python_services:
    restart: always
    container_name: backend
    build: ./backend/python
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    volumes: 
      - "./backend/python:/home/backend/app"
    ports:
    - 5001:80
  frontend:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true 
    volumes:
      - './frontend:/home/frontend/app'
    ports:
      - 5002:3000
    depends_on: 
      - python_services
    
    
    
  