apiVersion: v1
kind: Service
metadata:
  name: kh-backend
  labels:
    app: kh-backend
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: kh-backend
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kh-backend-config
  labels:
    app: kh-backend
data:
  APP_SETTINGS: "src.config.ProductionConfig"
  MONGO_URI: "mongodb://kh-mongo/hackathon"
  CELERY_BROKER_URL: "amqp://kh-rabbitmq"
  MAIL_PORT: "587"
  MAIL_USE_TLS: "true"
  MAIL_SERVER: "smtp.knighthacks.org"
  MAIL_USERNAME: "noreply@knighthacks.org"
  MAIL_PASSWORD: "supersecurepassword"
  MAIL_DEFAULT_SENDER: "noreply@knighthacks.org"
  SECRET_KEY: "viva la pluto"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kh-backend
spec:
  selector:
    matchLabels:
      app: kh-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: kh-backend
    spec:
      containers:
        - name: kh-backend
          image: <registry-name>.azurecr.io/backend
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 100m
          envFrom:
          - configMapRef:
              name: kh-backend-config
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kh-backend
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kh-backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
