apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: backend-port
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <registry-name>.azurecr.io/backend
          ports:
            - containerPort: 5000
              name: backend-port
          env:
            - name: APP_SETTINGS
              value: "src.config.ProductionConfig"
            - name: MONGO_URI
              value: "mongodb://mongo-service/hackathon"
            - name: CELERY_BROKER_URL
              value: "amqp://kh-rabbitmq"
            - name: MAIL_PORT
              value: 587
            - name: MAIL_USE_TLS
              value: "true"
            - name: MAIL_SERVER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MAIL_SERVER
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MAIL_PASSWORD
            - name: MAIL_DEFAULT_SENDER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MAIL_DEFAULT_SENDER
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SECRET_KEY
  selector:
    matchLabels:
      app: backend
