apiVersion: v1
kind: Service
metadata:
  name: kh-backend
  labels:
    app: kh-backend
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: kh-backend
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kh-backend
spec:
  selector:
    matchLabels:
      app: kh-backend
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kh-backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  template:
    metadata:
      labels:
        app: kh-backend
    spec:
      containers:
        - name: kh-backend
          image: <registry-name>.azurecr.io/backend
          ports:
            - containerPort: 5000
          env:
            - name: APP_SETTINGS
              value: "src.config.ProductionConfig"
            - name: MONGO_URI
              value: "mongodb://kh-mongo/hackathon"
            - name: CELERY_BROKER_URL
              value: "amqp://kh-rabbitmq"
            - name: MAIL_PORT
              value: 587
            - name: MAIL_USE_TLS
              value: "true"
            - name: MAIL_SERVER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MAIL_SERVER
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MAIL_PASSWORD
            - name: MAIL_DEFAULT_SENDER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MAIL_DEFAULT_SENDER
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SECRET_KEY