apiVersion: v1
kind: ConfigMap
metadata:
  name: kh-discordbot-config
  labels:
    app: kh-discordbot
data:
  DISCORD_GUILD: ""
  START_ROLE: ""
  KNIGHTHACKS: ""
  CODE_MESSAGE: ""
  LOGGING_CHANNEL_ID: ""
  KH_SERVER_ID: ""
  KH_HACKER_ROLE: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kh-discordbot
spec:
  selector:
    matchLabels:
      app: kh-discordbot
  replicas: 1
  template:
    metadata:
      labels:
        app: kh-discordbot
    spec:
      containers:
        - name: kh-discordbot
          image: <registry-name>.azurecr.io/discordbot
          envFrom:
          - configMapRef:
              name: kh-discordbot-config
          - secretRef:
              name: kh-discordbot-secret
