apiVersion: v1
kind: Secret
metadata:
  name: kh-backend-secret
type: Opaque
stringData:
  MAIL_SERVER: "smtp.knighthacks.org"
  MAIL_USERNAME: "noreply@knighthacks.org"
  MAIL_PASSWORD: "supersecurepassword"
  MAIL_DEFAULT_SENDER: "noreply@knighthacks.org"
  SECRET_KEY: "viva la pluto"
  SENTRY_DSN: ""
  NOTION_CRONJOB_USERNAME: "exampleusername"
  NOTION_CRONJOB_PASSWORD: "supersecurepassword"
  NOTION_TOKEN: ""
  NOTION_DB_ID: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: kh-discordbot-secret
type: Opaque
stringData:
  DISCORD_TOKEN: ""
  REDDIT_API_KEY: ""
  REDDIT_CLIENT_ID: ""
  REDDIT_USER_AGENT: ""
  WEATHER_API_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: kh-notionjob-secret
type: Opaque
stringData:
  KHUNAME: "exampleusername"
  KHPASSWD: "supersecurepassword"
#---
#apiVersion: v1
#kind: Secret
#metadata:
  #name: ingress-tls
#type: kubernetes.io/tls
#data:
  #tls.crt: ""
  #tls.key: ""
