apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  MAIL_SERVER: smtp.knighthacks.org
  MAIL_USERNAME: noreply@knighthacks.org
  MAIL_PASSWORD: supersecurepassword
  MAIL_DEFAULT_SENDER: noreply@knighthacks.org
  SECRET_KEY: viva la pluto
#---
#apiVersion: v1
#kind: Secret
#metadata:
  #name: ingress-tls
#type: kubernetes.io/tls
#data:
  #tls.crt: ""
  #tls.key: ""
