apiVersion: v1
kind: Service
metadata:
  name: kh-frontend
  labels:
    app: kh-frontend
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: kh-frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kh-frontend
spec:
  selector:
    matchLabels:
      app: kh-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: kh-frontend
    spec:
      containers:
        - name: kh-frontend
          image: <registry-name>.azurecr.io/frontend
          ports:              
            - containerPort: 80
