apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kh-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "ingress"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"

spec:
  tls:
  - hosts:
    - api.dev.torrentofshame.com
    - dev.torrentofshame.com
    secretName: ingress-tls
  rules:
  - host: api.dev.torrentofshame.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kh-backend
            port:
              number: 80
  - host: dev.torrentofshame.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kh-frontend
            port:
              number: 80
