apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: mongodb
  type: ClusterIP
---
apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: kh-mongo-bs-claim
spec:
  storageClassName: azureDisk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  volumes:
    - name: kh-mongo-storage
      persistantVolumeClaim:
        claimName: kh-mongo-bs-claim
  containers:
    - name: mongodb
      image: mongo
      ports:
        - containerPort: 27017
          name: mongodb-port
      volumeMounts:
        - mountPath: "/data/db"
          name: kh-mongo-storage
