FROM python:3.9.0-slim

WORKDIR /home/backend/app

COPY requirements-dev.txt .
RUN pip install -r requirements-dev.txt

COPY . .

ENTRYPOINT [ "python" ]
CMD [ "-m", "src", "run", "--host=0.0.0.0", "--port=5000" ]
