name: Python Linter

on: 
  pull_request:
    paths: 
      - "**.py"
defaults:
  run:
    working-directory: backend/python/

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Use flake8
      uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
      with:
          # The GitHub API token to create reviews with
          token: ${{ secrets.GITHUB_TOKEN }}
          # Fail if "new" violations detected or "any", default "new"
          failIf: new
          # Additional arguments to pass to flake8, default "." (current directory)
          args: "--ignore=E121,E123 ."

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Test the app
      run: |
        coverage run --source=src -m src test
        coverage xml
    - name: Comment Coverage
      uses: 5monkeys/cobertura-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 75
